module.exports = {
  'primary-color': '#0E5B87',
  'link-color': '#14A9FF',
  'success-color': '#52C41A',
  'warning-color': '#FAAD14',
  'error-color': '#FF4D4F',
  'heading-color': '#303133',
  'text-color': '#EBECEC',
  'text-color-secondary': '#909399',
  'disabled-color': '#DCDFE6',
  'border-radius-base': '4px',
  'border-color-base': '#0E5B87',
  'primary-5': '#0E5B87',
  'input-hover-border-color': '#0E5B87',
  'modal-footer-padding-horizontal': '48px',
  'label-color': '#AFB1B1',
  'component-background': 'transparent',
  'select-dropdown-bg': '#323E42',
  'select-item-selected-bg': '#455256',
  'select-item-active-bg': 'rgba(50, 62, 66, .5)',
  'select-item-selected-color': '#14A9FF',
  'calendar-bg': '#182529',
  'input-placeholder-color': '#535657',
  'table-header-bg': '#F0F2F5',
  'table-row-hover-bg': '#10191C',
  'table-border-color': '#323E42',
  'tabs-card-active-color': '#14A9FF',
  'tabs-highlight-color': '#14A9FF',
  'tabs-hover-color': '#14A9FF',
  'tabs-active-color': '#14A9FF',
  'tabs-ink-bar-color': '#14A9FF',
  'input-padding-horizontal': '8px',
  'modal-header-bg': '#090E0F',
  'modal-content-bg': '#090E0F',
  'modal-footer-bg': '#090E0F',
  'steps-background': '#090E0F',
  'message-notice-content-bg':'#F0F2F5',
  'modal-heading-color': '#EBECEC',
  'modal-header-border-color-split': 'transparent',
  'modal-footer-border-color-split': 'transparent',
  'modal-footer-padding-horizontal': '0',
  'modal-footer-padding-vertical': '0',
  'switch-color': '#00B42A',
  'switch-bg':'#EBECEC',
  'popover-bg': '#323E42',
  'disabled-bg': '#182529',
  'tree-node-selected-bg': 'transparent',
  'tree-node-hover-bg': 'transparent',
  'tree-title-height': '20px',
  'dropdown-menu-bg': '#323E42',
  'menu-item-color': '#EBECEC'
}